#!/bin/bash
# Author: jacky.yao
# Date Created: 12/04/2026
# Last Modified: 12/04/2026
 
# Description:
# Creates a backup in ~/bash_course folder of all files in the home directory

# Usage:
# backup_script
 
echo 'hello ${USER^}'
echo "I will now backup you home directory, $HOME"
current_dir=$(pwd)
echo "You are running this script from $current_dir"
echo "Therefore,I will save the backup in $current_dir"
#tar -cvf ~/bash_course/mybackup_"$(date +%d-%m-%Y_%H-%M_%S)".tar ~/* 2>/dev/null
tar -cf ${current_dir}/mybackup_"$(date +%d-%m-%Y_%H-%M_%S)".tar $(HOME)/* 2>/dev/null
echo "Backup Completed Cuccessfully"
exit 0
