#!/bin/bash
# Author: jacky.yao
# Date Created: 12/04/2026
# Last Modified: 12/04/2026
 
# Description:
# Creates a backup in ~/bash_course folder of all files in the home directory

# Usage:
# backup_script
tar -cvf ~/bash_course/mybackup_"$(date +%d-%m-%Y_%H-%M_%S)".tar ~/* 2>/dev/null
exit 0
